function visualizeMarkersOnSTL( ...
    robot_mesh, markers_body, plot_title)
%VISUALIZEMARKERSONSTL Plot body-frame markers on the robot STL.

    if nargin < 3
        plot_title = 'Reflective Marker Configuration';
    end

    vertices = robot_mesh.Points;
    faces    = robot_mesh.ConnectivityList;

    figure('Color', 'w');
    hold on;
    grid on;
    box on;
    axis equal;
    view(3);

    % Muted steel-blue mesh
mesh_color = [0.55 0.72 0.84];
edge_color = [0.35 0.48 0.58];

    trisurf(faces, ...
            vertices(:,1), ...
            vertices(:,2), ...
            vertices(:,3), ...
            'FaceColor', mesh_color, ...
            'FaceAlpha', 0.7, ...
            'EdgeColor', edge_color, ...
            'EdgeAlpha', 0.12);

    scatter3(markers_body(:,1), ...
             markers_body(:,2), ...
             markers_body(:,3), ...
             70, ...
             [0.90 0.10 0.10], ...
             'filled', ...
             'MarkerEdgeColor', 'k', ...
             'LineWidth', 0.6);

    for marker_index = 1:size(markers_body,1)
        text(markers_body(marker_index,1), ...
             markers_body(marker_index,2), ...
             markers_body(marker_index,3), ...
             sprintf('  M%d', marker_index), ...
             'FontSize', 10, ...
             'FontWeight', 'bold', ...
             'Color', [0.08 0.08 0.08]);
    end

    xlabel('Body X (m)');
    ylabel('Body Y (m)');
    zlabel('Body Z (m)');
    title(plot_title);

    camlight('headlight');
    lighting gouraud;
end